//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> ProcedureId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Procedure Procedure { get; set; }
    }
}
